### ISSUE TITLE
File Count on Directory GET

### ISSUE THREAD

**Issue by lorenzhohmann** [Thunderklaud/thunder-server#17]
Please add an variable "fileCount" with the amount of files of the current directory. Otherwise I always have to make an additional request to the server or save it somehow in a cumbersome way... 👍

**Comment by binsky08** [comment]
Just calculate the size of the files object you can get from the server when listing directory contents.
Or why do you need a extra value for it?

**Comment by lorenzhohmann** [comment]
I want to know the child count of the folder without calling the route for the directory. So if A is the parent of B I need to call the GET directory of B to get it child count of A. You know what I mean...? xD

**Comment by binsky08** [comment]
GET {{ _.srv }}/v1/data/directory returns you a json object containing a files list

**Comment by lorenzhohmann** [comment]
I know. But I want to get the child count without requesting the folder. E.g. with this result I want to know how many childs "ScreenToGif" has.

{
    "dirs": [
        {
            "id": {
                "$oid": "63b93cda24aebb1d0dd3b787"
            },
            "name": "ScreenToGif"
        }
    ],
    "files": []
}
