### ISSUE TITLE
Allow file upload to root directory

### ISSUE THREAD

**Issue by lorenzhohmann** [Thunderklaud/thunder-server#19]
When try to add a file to the root path (directory parameter empty) the error "Query field directory is not parseable" occurs.

**Comment by binsky08** [comment]
The JWT contains that required root dir id as a custom claim

**Comment by lorenzhohmann** [comment]
Then I would have to decode the JWT locally. For that I would need the secret... Or is there already a route for that?

**Comment by binsky08** [comment]
The parts between the dots are just base64 encoded. You need the middle-part.

### Example:

From:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NzI4NjM5NTYsImlhdCI6MTY3Mjg2MDM1Niwic3ViIjoiNjNiNWQyYmY1YTBlMjk2NWRiNzNjYjE2IiwidGh1bmRlcl9yb290X2Rpcl9pZCI6eyIkb2lkIjoiNjNiNWQyYmY1YTBlMjk2NWRiNzNjYjFiIn19.dIFCHiUSGpHMIAzAqfozw2oMSkXQ8L439mDstIBHX5Id2JhOUFDoZ-lBfaahLUsoSijXKkqDrkHClrEaNjl4Rw

you need eyJleHAiOjE2NzI4NjM5NTYsImlhdCI6MTY3Mjg2MDM1Niwic3ViIjoiNjNiNWQyYmY1YTBlMjk2NWRiNzNjYjE2IiwidGh1bmRlcl9yb290X2Rpcl9pZCI6eyIkb2lkIjoiNjNiNWQyYmY1YTBlMjk2NWRiNzNjYjFiIn19

and decode with
`echo "eyJleHAiOjE2NzI4NjM5NTYsImlhdCI6MTY3Mjg2MDM1Niwic3ViIjoiNjNiNWQyYmY1YTBlMjk2NWRiNzNjYjE2IiwidGh1bmRlcl9yb290X2Rpcl9pZCI6eyIkb2lkIjoiNjNiNWQyYmY1YTBlMjk2NWRiNzNjYjFiIn19" | base64 --decode`
to
`{"exp":1672863956,"iat":1672860356,"sub":"63b5d2bf5a0e2965db73cb16","thunder_root_dir_id":{"$oid":"63b5d2bf5a0e2965db73cb1b"}}`

The root dir id is `thunder_root_dir_id["$oid"]`

No secret needed
